// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { Config, ConfigData } from "./tables/Config.sol";
import { Admin } from "./tables/Admin.sol";
import { Name } from "./tables/Name.sol";
import { NameExists } from "./tables/NameExists.sol";
import { Verifier, VerifierData } from "./tables/Verifier.sol";
import { MatchEntityCounter } from "./tables/MatchEntityCounter.sol";
import { MatchConfig, MatchConfigData } from "./tables/MatchConfig.sol";
import { MatchAllowed } from "./tables/MatchAllowed.sol";
import { MatchArrangement, MatchArrangementData } from "./tables/MatchArrangement.sol";
import { MatchTurn, MatchTurnData } from "./tables/MatchTurn.sol";
import { MatchPlayers } from "./tables/MatchPlayers.sol";
import { MatchPlayer, MatchPlayerData } from "./tables/MatchPlayer.sol";
import { MatchPlayerByAddress } from "./tables/MatchPlayerByAddress.sol";
import { SeasonPassIndex } from "./tables/SeasonPassIndex.sol";
import { SeasonPassConfig, SeasonPassConfigData } from "./tables/SeasonPassConfig.sol";
import { SeasonTimes, SeasonTimesData } from "./tables/SeasonTimes.sol";
import { SeasonPassSale, SeasonPassSaleData } from "./tables/SeasonPassSale.sol";
import { SeasonPassLastSaleAt } from "./tables/SeasonPassLastSaleAt.sol";
