// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAccessControlSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAccessControlSystem {
  function isAllowed(bytes32 matchEntity, address account) external view returns (bool);

  function setAllowList(bytes32 matchEntity, address[] memory accounts) external;
}
