// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SetupPubSignals, MovePubSignals, AttackPubSignals, DefensePubSignals } from "./../../libraries/LibVerifier.sol";

/**
 * @title IMoveSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMoveSystem {
  function setup(
    bytes32 matchEntity,
    bytes32 playerEntity,
    uint[8] calldata proof,
    SetupPubSignals calldata pubSignals
  ) external;

  function move(
    bytes32 matchEntity,
    bytes32 playerEntity,
    uint[8] calldata proof,
    MovePubSignals calldata pubSignals
  ) external;

  function attack(
    bytes32 matchEntity,
    bytes32 playerEntity,
    uint[8] calldata proof,
    AttackPubSignals calldata pubSignals
  ) external;

  function defense(
    bytes32 matchEntity,
    bytes32 playerEntity,
    uint[8] calldata proof,
    DefensePubSignals calldata pubSignals
  ) external;

  function arbitrate(bytes32 matchEntity, bytes32 playerEntity) external;
}
