// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IAccessControlSystem } from "./IAccessControlSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { IMatchSystem } from "./IMatchSystem.sol";
import { IMoveSystem } from "./IMoveSystem.sol";
import { INameSystem } from "./INameSystem.sol";
import { ISeasonPassSystem } from "./ISeasonPassSystem.sol";
import { IWithdrawSystem } from "./IWithdrawSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAccessControlSystem,
  IIncrementSystem,
  IMatchSystem,
  IMoveSystem,
  INameSystem,
  ISeasonPassSystem,
  IWithdrawSystem
{}
